[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
lazy_static = "1.4.0"
mockall = "0.11.2"
tokio = { version = "1.20.1", features = ["full"] }
